### ISSUE TITLE
Samples results

### ISSUE THREAD

**Issue by Quocvuong82** [b04901014/waveglow-tensorflow#3]
I trained this model and get good results after 100k
[103k steps.zip](https://github.com/b04901014/waveglow-tensorflow/files/2698220/103k.steps.zip)
[151k steps.zip](https://github.com/b04901014/waveglow-tensorflow/files/2698221/151k.steps.zip)
[201k steps.zip](https://github.com/b04901014/waveglow-tensorflow/files/2698222/201k.steps.zip)
[Org.zip](https://github.com/b04901014/waveglow-tensorflow/files/2698223/Org.zip)

(used 9982 samples (8.5 hrs) : valsplit ~ 0.9, batchsize = 2, wavetimestep = 16384, after 200k steps ~ 40 epochs)

**Comment by b04901014** [comment]
Thank you for providing some results of other dataset with details.
Seems the model still works fine and the sample quality is improving over iterations.

**Comment by StephenHuang1215** [comment]
Wow, It's amazing!

**Comment by StephenHuang1215** [comment]
Wow, It's amazing!

**Comment by Quocvuong82** [comment]
This is a great implementation for waveglow!!!!
@b04901014 thank you for this hard work.

**Comment by Quocvuong82** [comment]
Please note that:
I do not use_weight_norm (use_weight_norm=False),
preemphasis wav signal before compute mel spectrogram and use preemphasis wav signal for model output prediction.
Sorry I'm not fluent in English.
